[project]
name = "taki-telsist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pytelegrambotapi>=4.23.0", "python-dotenv>=1.0.1"]
