[project]
name = "taki-telsist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.14.0",
    "argparse>=1.4.0",
    "dishka>=1.4.0",
    "pydantic-settings>=2.6.1",
]
